grase_radmin:
    resource: "@GraseRadminBundle/Resources/config/routing.yml"
    prefix: /admin
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /admin